cart/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('cart.views', 
	(r'^$', 'show_cart', {'template_name':'shop/cart/cart.html'}, 'show_cart')
)

mall/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from shoplist.views import *
from shop.views import *
import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    ('^$', shoplist),
    url(r'^shop/(?P<slug>[\w\d]+)/$', shop_main, name='shop_main'),
    url(r'^shop/(?P<slug>[-A-Za-z0-9_]+)/categories/(?P<category_slug>[-A-Za-z0-9_]+)$', category, name='category'),
    url(r'^shop/(?P<slug>[-A-Za-z0-9_]+)/products/(?P<product_slug>[-A-Za-z0-9_]+)$', product, name='product'),
    (r'^cart/', include('cart.urls')),
    url(r'^cart/checkout/', 'cart.views.checkout')
)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),
)

shop/models.py
from django.db import models
from shoplist.models import *
from mall import settings
import os

class Product_Category(models.Model):
    shop_slug = models.ForeignKey(Shops)
    name =  models.CharField(max_length=50)
    category_slug = models.SlugField(("Slug"), help_text=("Used for URLs"), blank=True)
    category_parent = models.ForeignKey('self', blank=True, null=True, related_name='child')
    meta = models.TextField(("Meta Description"), blank=True, null=True,
        help_text=("Meta description for this category"))
    description = models.TextField(("Description"), blank=True,
        help_text="Optional")
    ordering = models.IntegerField(("Ordering"), default=0, help_text=("Override alphabetical order in category display"))
    is_active = models.BooleanField(("Active"), default=True, blank=True)
    
    class Meta:
        verbose_name_plural = 'Product Categories'
    
    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('category', (), {
            'slug': self.shop_slug,
            'category_slug': self.category_slug})

class Product(models.Model):
    shop_slug = models.ForeignKey(Shops)
    product_category = models.ManyToManyField(Product_Category, blank=True, verbose_name=("Category"))
    name = models.CharField(("Name"), max_length=255, blank=False)
    product_slug = models.SlugField(("Slug"), help_text=("Used for URLs"), blank=True)
    sku = models.CharField(("SKU"), max_length=255, blank=True, null=True)
    meta_keywords = models.TextField(("meta keywors"), max_length=200, default='', blank=True)
    meta_description = models.TextField(("meta description"), max_length=400, default='', blank=True)
    short_description = models.TextField(("Short description of product"), 
                                        help_text=("This should be a 1 or 2 line description in the default site language for use in product listing screens"), 
                                        max_length=200, default='', blank=True)
    description = models.TextField(("Description of product"), help_text=("This field can contain HTML and should be a few paragraphs in the default site language explaining the background of the product, and anything that would help the potential customer make their purchase."), 
                                    default='', blank=True)
    items_in_stock = models.DecimalField(("Qty on stock"), max_digits=18, decimal_places=6, default='0')
    date_added = models.DateField(("Date added"), null=True, blank=True)
    active = models.BooleanField(("Active"), default=True, help_text=("This will determine whether or not this product will appear on the site"))
    price = models.DecimalField(max_digits=14, decimal_places=6)
    featured = models.BooleanField(("Featured"), default=False, help_text=("Featured items will show on the front page"))
    ordering = models.IntegerField(("Ordering"), default=0, help_text=("Override alphabetical order in category display"))  
    total_sold = models.DecimalField(("Qty Sold"), max_digits=18, decimal_places=6, default='0')
    image = models.ImageField(upload_to='products/images/')
    
    def __unicode__(self):
        return self.name
    
    @models.permalink
    def get_absolute_url(self):
        return ('product', (), {
            'slug': self.shop_slug,
            'product_slug': self.product_slug})

class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images')
    image = models.ImageField(upload_to='products/images/')

class ProductAttributes(models.Model):
    product = models.ForeignKey(Product, related_name='attributes')
    attribute = models.CharField(("Attribute name"), max_length=45, blank=True)
    attribute_value = models.TextField(("Attribute value"), max_length=77, blank=True)

shop/forms.py
# -*- coding: UTF-8 -*-
from django import forms
from shop.models import Product

class ProductAdminForm(forms.ModelForm):
	class Meta:
		model = Product
	def clean_price(self):
		if self.cleaned_data['price'] <= 0:
			raise forms.ValidationError('Price must be greater than zero.')
		return self.cleaned_data['price']

class ProductAddToCartForm(forms.Form):
	quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size':'2',
		'value':'1', 'class':'quantity', 'maxlength':'5'}),
		error_messages={'invalid':'Please enter a valid quantity.'},
		min_value=1)
	product_slug = forms.CharField(widget=forms.HiddenInput())
	
	# override the default __init__ so we can set the request
	def __init__(self, request=None, *args, **kwargs):
		self.request = request
		super(ProductAddToCartForm, self).__init__(*args, **kwargs)
	
	# custom validation to check for cookies
	def clean(self):
		if self.request:
			if not self.request.session.test_cookie_worked():
				raise forms.ValidationError("Cookies must be enabled.")
		return self.cleaned_data

shop/views.py
# -*- coding: UTF-8 -*-
from django.shortcuts import render_to_response, get_object_or_404
from django.core import urlresolvers
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from shoplist.models import *
from shop.models import *
from shop.forms import ProductAddToCartForm
from cart import cart


def shop_main(request, slug):
    if request.method == "POST":
        uname, pswd = request.POST['username'], request.POST['password']
        user = authenticate(username=uname, password=pswd)
        if user is not None:
            if user.is_active:
                login(request, user)
                url = request.META.get('HTTP_REFERER', None)
                return HttpResponseRedirect(url)
    else:
        shop_data = Shops.objects.get(slug=slug)
        shop_slug = shop_data.id
        categories = Product_Category.objects.filter(shop_slug=shop_slug)
        login_form = AuthenticationForm
        featured_products = Product.objects.filter(shop_slug=shop_slug, featured=1)
        featured_items = []
        for item in featured_products:
            featured_items.append((item.name, ProductImage.objects.filter(product=item.id)[0].image))
        return render_to_response('shop/base.html', RequestContext(request, {'shop_data':shop_data, 'categories':categories, 
                                                                            'featured_products':featured_items,
                                                                            'login':login_form, 'request':request}))
        # return render_to_response('shop/base.html', locals(), context_instance=RequestContext(request))

def category(request, slug, category_slug):
    if request.method == "POST":
        uname, pswd = request.POST['username'], request.POST['password']
        user = authenticate(username=uname, password=pswd)
        if user is not None:
            if user.is_active:
                login(request, user)
                url = request.META.get('HTTP_REFERER', None)
                return HttpResponseRedirect(url)
    else:
        shop_data = Shops.objects.get(slug=slug)
        shop_slug = shop_data.id
        categories = Product_Category.objects.filter(shop_slug=shop_slug)
        category_data = Product_Category.objects.get(category_slug=category_slug)
        category_products = Product.objects.filter(product_category=category_data.id)
        login_form = AuthenticationForm
        return render_to_response('shop/category.html', RequestContext(request, 
                                                                        {'shop_data':shop_data, 'categories':categories, 
                                                                        'category':category_data, 'products':category_products,
                                                                        'login':login_form, 'request':request,}))
    
def product(request, slug, product_slug):
    p = get_object_or_404(Product, product_slug=product_slug)
    if request.method == 'POST':
        post_data = request.POST.copy()
        form = ProductAddToCartForm(request, post_data)
        #check if posted data is valid
        if form.is_valid():
            #add to cart and redirect to cart page
            cart.add_to_cart(request)
        # if test cookie worked, get rid of it
        if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
        url = urlresolvers.reverse('show_cart')
        return HttpResponseRedirect(url)
    else:
        form = ProductAddToCartForm()
        shop_data = Shops.objects.get(slug=slug)
        product_data = Product.objects.get(product_slug = product_slug)
        shop_slug = shop_data.id
        categories = Product_Category.objects.filter(shop_slug=shop_slug)
        # assign the hidden input the product slug
        form.fields['product_slug'].widget.attrs['value'] = product_slug
        # set the test cookie on our first GET request
        request.session.set_test_cookie()
        images = ProductImage.objects.filter(product=product_data.id)
        login_form = AuthenticationForm
        return render_to_response('shop/product.html', RequestContext(request, {'shop_data':shop_data, 'product_data':product_data, 
                                                                                'images':images, 'form':form, 'login':login_form, 
                                                                                'categories':categories, 'request':request}))

mall/templates/shop/base.html
{% load thumb %}
{% load catalog_tags %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>{{ shop_data.title }}</title>
        <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/shop_default/styles.css" />
	</head>
	<body>
        <div class="userpannel">
            {% if user.username %} 
            Добро пожаловать, {{ user.username }}
            {% else %} 
            <form method="post" action="">
                {% csrf_token %}
                {{ login.as_p }}
                <br />
                <input type="submit" value="Login" name="submit" alt="Login" />
            </form>
            {% endif %}
        </div>
        <div class="cart_box">
            {% cart_box request %}
        </div>
        <div class="main">
		{% block content %}
        <h1>{{ shop_data.title }}</h1>
        <h2>{{ shop_data.description }}</h2>
        <a href="http://localhost:8000">Главная</a>
    	    <p>Категории:</p>
        		<ul> {% for category in categories %}
            		<li> <a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
             		{% endfor %}
        		</ul>
        	{% if featured_products %}
            <p>Специалньное предложение:</p>
                {% for product, image in featured_products %}
                <ul>
                    <li>{{ product }} <img alt="product image" title="{{ product }}" src="{{ image|thumbnail}}"></li>
                </ul>
                {% endfor %}
        	{% else %}
            <p>На данный момент нет специальных предложений.</p>
        	{% endif %}
		{% endblock %}
        </div>
        <script type="text/javascript" src="{{ MEDIA_URL }}jquery-1.10.1.min.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}scripts.js"></script>
	</body>
</html>

mall/templates/shop/category.html
{% extends "shop/base.html" %}
{% load catalog_tags %}

{% block content %}
        <h1>{{ shop_data.title }}</h1>
        <h2>{{ category.name }}</h2>
        <h3>{{ test }}</h3>
        <p>Категории:</p>
        <ul> {% for category in categories %}
            <li> <a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
             {% endfor %}
        </ul>
        {% if products %}
        <p>Продукты в данной категории:</p>
        <ul>
            {% for product in products%}
            <li><a href="{{ product.get_absolute_url }}">{{ product.name }} -- {{ product.price }} USD</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <p>В данной категории пока нет продуктов.</p>
        {% endif %}
{% endblock %}

mall/templates/shop/checkout.html
{% extends "shop/base.html" %}
{% load catalog_tags %}

{% block content %}
	<h1>This is Check-Out Page!</h1>
{% endblock %}

mall/templates/shop/delete_ME-main.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ shop_data.title }}</title>
</head>
    <body>
        <h1>{{ shop_data.title }}</h1>
        <p>{{ shop_data.description }}</p>
        <p>Категории:</p>
        <ul> {% for category in categories %}
            <li> <a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
             {% endfor %}
        </ul>
        {% if featured_products %}
            <p>Специалньное предложение:</p>
                {% for product, image in featured_products %}
                <ul>
                    <li>{{ product }} <img alt="product image" title="{{ product }}" src="http://localhost:8000/static/{{ image|cut:"/home/martyn/Documents/djcode/mall/shop/" }}"></li>
                </ul>
                {% endfor %}
        {% else %}
            <p>На данный момент нет специальных предложений.</p>
        {% endif %}
    </body>
</html>

mall/templates/shop/product.html
{% extends "shop/base.html" %}
{% load thumb %}
{% block content %}
        <h1>{{ product_data.name }}</h1>
        {% if images %}
            {% for image in images %}
                <img alt="product image" title="{{ product_data.name }}" src="{{ image.image|thumbnail:'150x150' }}">
            {% endfor %}
        {% endif %}
    <p>Цена: {{ product_data.price }} {{ shop_data.currency }}</p>
    <form method="post" action="" class="cart">{% csrf_token %}
		<p><label for="id_quantity">Количество:</label> 
            {{ form.quantity }}
            {{ form.product_slug }}
		<br />
		<input type="submit" value="Купить" name="submit" alt="Add To Cart" />
	</form>
    <p>Категории:</p>
        <ul> {% for category in categories %}
            <li> <a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
             {% endfor %}
        </ul>
{% endblock %}
</html>